config/routes.rb
require "platform/constraints/subdomain_required"

Platform::Engine.routes.draw do
	constraints(Platform::Constraints::SubdomainRequired) do
		scope :module => "account" do
			root :to => "dashboard#index", :as => :account_root
		end
	end
	root "dashboard#index"

	get "/sign_up", :to => "accounts#new", :as => :sign_up

	post "/accounts", :to => "accounts#create", :as => :accounts


end

app/models/platform/account.rb
module Platform
	class Account < ActiveRecord::Base
		belongs_to :owner, :class_name => "Platform::User"
		accepts_nested_attributes_for :owner

		validates :subdomain, :presence => true, :uniqueness => true

		EXCLUDED_SUBDOMAINS = %w(admin)
		validates_exclusion_of :subdomain, :in => EXCLUDED_SUBDOMAINS,
		:message => "is not allowed. Please choose another subdomain."

		validates_format_of :subdomain, :with => /\A[\w\-]+\Z/i,
		:message => "is not allowed. Please choose another subdomain."

		before_validation do
			self.subdomain = subdomain.to_s.downcase
		end

	end
end

app/controllers/platform/accounts_controller.rb
require_dependency "platform/application_controller"

module Platform
	class AccountsController < ApplicationController

		def new
			@account = Platform::Account.new
			@account.build_owner
		end


		def create
			@account = Platform::Account.new(account_params)
			if @account.save
				env["warden"].set_user(@account.owner, :scope => :user)
				env["warden"].set_user(@account, :scope => :account)
				flash[:success] = "Your account has been successfully created."
				redirect_to platform.root_url(:subdomain => @account.subdomain)
			else
				flash[:error] = "Sorry, your account could not be created."
				render :new
			end
		end


		private
		def account_params
			params.require(:account).permit(:name, :subdomain,
				{ :owner_attributes => [
					:email, :password, :password_confirmation
					]}
					)
		end

	end
end

app/controllers/platform/application_controller.rb
module Platform
  class ApplicationController < ActionController::Base

    def current_account
      if user_signed_in?
        @current_account ||= begin
          account_id = env["warden"].user(:scope => :account)
          Platform::Account.find(account_id)
        end
      end
    end

    helper_method :current_account

    def current_user
      if user_signed_in?
        @current_user ||= begin
          user_id = env["warden"].user(:scope => :user)
          Platform::User.find(user_id)
        end
      end
    end

    helper_method :current_user

    def user_signed_in?
      env["warden"].authenticated?(:user)
    end

    helper_method :user_signed_in?
  end
end

app/controllers/platform/dashboard_controller.rb
require_dependency "platform/application_controller"

module Platform
  class DashboardController < ApplicationController
  end
end

app/helpers/platform/accounts_helper.rb
module Platform
  module AccountsHelper
  end
end

app/helpers/platform/application_helper.rb
module Platform
  module ApplicationHelper
  end
end

app/helpers/platform/dashboard_helper.rb
module Platform
  module DashboardHelper
  end
end

app/views/layouts/platform/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Platform</title>
	<% if user_signed_in? %>
	Signed in as <%= current_user.email %>
	<% end %>

	<% flash.each do |k,v| %>
	<div class='flash <%= k %>'><%= v %></div>
	<% end %>

	<%= stylesheet_link_tag    "platform/application", media: "all" %>
	<%= javascript_include_tag "platform/application" %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/platform/accounts/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@account) do |account| %>
<%= account.error_messages %>
<p>
<%= account.label :name %><br>
<%= account.text_field :name %>
</p>
<p>
<%= account.label :subdomain %><br>
<%= account.text_field :subdomain %>
</p>
<%= account.fields_for :owner do |owner| %>
<p>
<%= owner.label :email %><br>
<%= owner.email_field :email %>
</p>
<p>
<%= owner.label :password %><br>
<%= owner.password_field :password %>
</p>
<p>
<%= owner.label :password_confirmation %><br>
<%= owner.password_field :password_confirmation %>
</p>
<% end %>
<%= account.submit %>
<% end %>

app/views/platform/dashboard/index.html.erb
<%= link_to "Account Sign Up", sign_up_path %>